name: miniproject
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^1.0.0
  animated_splash_screen: ^1.0.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  url_launcher: ^6.1.7
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:  # This line should be inside the `flutter:` block
    - assets/cafe_logo.json
    - assets/login_up.png
    - assets/login_logo.png
    - assets/espresso.jpg
    - assets/Latte.jpg
    - assets/americano.jpg
    - assets/Capuccino.jpg
    - assets/profile.jpg